# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/FloriGod/Development/metric_field

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/FloriGod/Development/metric_field

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/FloriGod/Development/metric_field/CMakeFiles /Users/FloriGod/Development/metric_field//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/FloriGod/Development/metric_field/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named metric_field

# Build rule for target.
metric_field: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metric_field
.PHONY : metric_field

# fast build rule for target.
metric_field/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/build
.PHONY : metric_field/fast

#=============================================================================
# Target rules for targets named metric_field_lib

# Build rule for target.
metric_field_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metric_field_lib
.PHONY : metric_field_lib

# fast build rule for target.
metric_field_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/build
.PHONY : metric_field_lib/fast

#=============================================================================
# Target rules for targets named OpenVolumeMesh

# Build rule for target.
OpenVolumeMesh: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OpenVolumeMesh
.PHONY : OpenVolumeMesh

# fast build rule for target.
OpenVolumeMesh/fast:
	$(MAKE) $(MAKESILENT) -f _deps/ovm-build/src/CMakeFiles/OpenVolumeMesh.dir/build.make _deps/ovm-build/src/CMakeFiles/OpenVolumeMesh.dir/build
.PHONY : OpenVolumeMesh/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/metric_field.o: src/metric_field.cpp.o
.PHONY : src/metric_field.o

# target to build an object file
src/metric_field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/metric_field.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/metric_field.cpp.o
.PHONY : src/metric_field.cpp.o

src/metric_field.i: src/metric_field.cpp.i
.PHONY : src/metric_field.i

# target to preprocess a source file
src/metric_field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/metric_field.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/metric_field.cpp.i
.PHONY : src/metric_field.cpp.i

src/metric_field.s: src/metric_field.cpp.s
.PHONY : src/metric_field.s

# target to generate assembly for a file
src/metric_field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/metric_field.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/metric_field.cpp.s
.PHONY : src/metric_field.cpp.s

src/other_fields.o: src/other_fields.cpp.o
.PHONY : src/other_fields.o

# target to build an object file
src/other_fields.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/other_fields.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/other_fields.cpp.o
.PHONY : src/other_fields.cpp.o

src/other_fields.i: src/other_fields.cpp.i
.PHONY : src/other_fields.i

# target to preprocess a source file
src/other_fields.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/other_fields.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/other_fields.cpp.i
.PHONY : src/other_fields.cpp.i

src/other_fields.s: src/other_fields.cpp.s
.PHONY : src/other_fields.s

# target to generate assembly for a file
src/other_fields.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/other_fields.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/other_fields.cpp.s
.PHONY : src/other_fields.cpp.s

src/predicates.o: src/predicates.c.o
.PHONY : src/predicates.o

# target to build an object file
src/predicates.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/predicates.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/predicates.c.o
.PHONY : src/predicates.c.o

src/predicates.i: src/predicates.c.i
.PHONY : src/predicates.i

# target to preprocess a source file
src/predicates.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/predicates.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/predicates.c.i
.PHONY : src/predicates.c.i

src/predicates.s: src/predicates.c.s
.PHONY : src/predicates.s

# target to generate assembly for a file
src/predicates.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/predicates.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field_lib.dir/build.make CMakeFiles/metric_field_lib.dir/src/predicates.c.s
.PHONY : src/predicates.c.s

src/tests.o: src/tests.cpp.o
.PHONY : src/tests.o

# target to build an object file
src/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/tests.cpp.o
.PHONY : src/tests.cpp.o

src/tests.i: src/tests.cpp.i
.PHONY : src/tests.i

# target to preprocess a source file
src/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/tests.cpp.i
.PHONY : src/tests.cpp.i

src/tests.s: src/tests.cpp.s
.PHONY : src/tests.s

# target to generate assembly for a file
src/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metric_field.dir/build.make CMakeFiles/metric_field.dir/src/tests.cpp.s
.PHONY : src/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... OpenVolumeMesh"
	@echo "... metric_field"
	@echo "... metric_field_lib"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/metric_field.o"
	@echo "... src/metric_field.i"
	@echo "... src/metric_field.s"
	@echo "... src/other_fields.o"
	@echo "... src/other_fields.i"
	@echo "... src/other_fields.s"
	@echo "... src/predicates.o"
	@echo "... src/predicates.i"
	@echo "... src/predicates.s"
	@echo "... src/tests.o"
	@echo "... src/tests.i"
	@echo "... src/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

